
CREATE DATABASE KUMOBD

USE KUMOBD 

CREATE TABLE CATEGORÍA(
Id_Categoria int identity (1,1) PRIMARY KEY,
NombreCat varchar(50) not null)


CREATE TABLE PRODUCTO (
Id_Producto INT IDENTITY(1,1) PRIMARY KEY,
NombrePr varchar(30) NOT NULL,
Precio decimal(10,2) not null,
Id_Categoria int,
constraint FK_CATEGORÍA
FOREIGN KEY (Id_Categoria) REFERENCES CATEGORÍA(Id_Categoria))

CREATE TABLE INVENTARIO(
Id_Inv int identity (1,1) PRIMARY KEY,
cant_disp int,
Id_Producto int,
constraint FK_PRODUCTO
FOREIGN KEY (Id_Producto) REFERENCES PRODUCTO(Id_Producto))

CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
Nombres_cl varchar (50),
Apellidos varchar (50),
Telefono varchar (15),
Fecha_Reg DATETIME DEFAULT GETDATE())

CREATE TABLE PEDIDOS(
Id_Pedido INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    Fecha DATETIME DEFAULT GETDATE(),
    Total DECIMAL(10,2),
    MetodoPago VARCHAR(20),
    CONSTRAINT FK_PEDIDOS_CLIENTES FOREIGN KEY (ID_CLIENTE) 
    REFERENCES CLIENTES(ID_CLIENTE))

CREATE TABLE DET_PEDIDOS(
Id_Detalle INT IDENTITY(1,1) PRIMARY KEY,
    Id_Pedido INT NOT NULL,
    Id_Producto INT NOT NULL,
    Cantidad INT NOT NULL,
    PrecioVentaMomento DECIMAL(10,2) NOT NULL, 
    CONSTRAINT FK_Detalle_Pedido FOREIGN KEY (Id_Pedido) 
    REFERENCES PEDIDOS(Id_Pedido),
    CONSTRAINT FK_Detalle_Producto FOREIGN KEY (Id_Producto) 
    REFERENCES PRODUCTO(Id_Producto))

CREATE TABLE VENTAS(
Id_Venta INT IDENTITY(1,1) PRIMARY KEY,
    Fecha DATETIME DEFAULT GETDATE(),
    LugarBazar VARCHAR(100),
    Id_Producto INT NOT NULL,
    Id_Cliente INT DEFAULT 1,
    Cantidad INT NOT NULL,
    PrecioVenta DECIMAL(10,2),  
    CONSTRAINT FK_Venta_Producto FOREIGN KEY (Id_Producto) REFERENCES PRODUCTO(Id_Producto),
    CONSTRAINT FK_Venta_Cliente FOREIGN KEY (Id_Cliente) REFERENCES CLIENTES(Id_Cliente))